# Розв'язок систем лінійних рівнянь

# Вхідні дані

In [125]:
import numpy as np
from scipy import linalg

In [126]:
n = 40
m = 4
l = 0
k = 4
i = 6
j = 0
g = 4

A = np.array([[0.3*(n+1), -0.2*m, 1.1*k, -0.4*i, 1.5*(30+j), -0.15*g],
[0.21*(40+n), -0.35*m, -2.1*k, -0.3*i, -4.5*j, 0.15*g], 
[1.1*n, -0.5*m, 1.4*k, -0.21*(54+i), 0.5, -0.75*g],
[5.2*n, 0.1*m, -0.2*(40+k), 0.1*i, -1.25*j, -1.05*g], 
[0.1*n, -0.9*(50+m), 1.04*k, -0.4*i, 0.8, -0.12*g],
[0.62, 0.3*m, -1.8*k, -0.41*i, 2.5*j, 0.2*(61+g)]])

b = np.array([l, -k, n, -m, i, j])

In [127]:
A

array([[ 12.3 ,  -0.8 ,   4.4 ,  -2.4 ,  45.  ,  -0.6 ],
       [ 16.8 ,  -1.4 ,  -8.4 ,  -1.8 ,  -0.  ,   0.6 ],
       [ 44.  ,  -2.  ,   5.6 , -12.6 ,   0.5 ,  -3.  ],
       [208.  ,   0.4 ,  -8.8 ,   0.6 ,  -0.  ,  -4.2 ],
       [  4.  , -48.6 ,   4.16,  -2.4 ,   0.8 ,  -0.48],
       [  0.62,   1.2 ,  -7.2 ,  -2.46,   0.  ,  13.  ]])

In [128]:
b

array([ 0, -4, 40, -4,  6,  0])

# Діагональне перевершення матриці

In [129]:
def make_diagonally_dominant(matrix):
    for i in np.arange(matrix.shape[0]):
        while(abs(matrix[i][i]) <= (np.sum(np.abs(matrix)[i]) - abs(matrix[i][i]))):
            matrix[i][i] += 1

make_diagonally_dominant(A)

# Точні методи розв'язку

In [130]:
np.linalg.det(A)

5000577053.357181

# Метод Крамера

In [131]:
def solve_using_cramers_rule(matrix, coefficients_vector):
    x = np.array([])
    for i in np.arange(matrix.shape[0]):
        matrix_i = np.copy(np.transpose(matrix))
        matrix_i[i] = coefficients_vector
        matrix_i = np.transpose(matrix_i)
        x_i = np.linalg.det(matrix_i)/np.linalg.det(matrix)
        x = np.append(x, x_i)
    return x

x = solve_using_cramers_rule(A, b)

In [132]:
x

array([-0.40792601,  0.42119903,  1.05068463,  0.41796394,  0.41876593,
        0.6415843 ])

# За допомогою оберненої матриці

In [133]:
A_inverse = np.copy(np.linalg.inv(A))

In [134]:
A_inverse

array([[ 5.86862881e-02, -7.40735983e-02, -1.11008268e-02,
        -1.05682727e-03, -4.40691062e-02,  1.59704662e-03],
       [-5.37845772e-02,  1.03124327e-01,  1.49423096e-02,
         1.52162337e-03,  4.03484083e-02, -1.81233536e-03],
       [-5.61792682e-02,  7.16522102e-02,  2.73264712e-02,
         2.01167421e-03,  4.20468868e-02,  2.60862030e-03],
       [-5.79750610e-02,  7.30876219e-02,  1.17907720e-02,
         5.62131334e-03,  4.35281331e-02,  9.52096991e-05],
       [-4.63757751e-02,  8.70951066e-02,  1.15910862e-02,
         1.40974833e-03,  5.15236511e-02, -1.12745962e-03],
       [-3.99194913e-02,  4.75283002e-02,  1.65159717e-02,
         2.08782846e-03,  2.99016576e-02,  7.84769935e-02]])

In [135]:
np.matmul(A,A_inverse)

array([[ 1.00000000e+00, -3.22513505e-17, -6.58997085e-17,
        -2.64949101e-17, -4.80895287e-16,  1.00692120e-17],
       [-2.32954334e-16,  1.00000000e+00,  2.07968982e-17,
        -2.98836029e-17, -2.44219126e-16, -1.00692120e-17],
       [ 4.02455846e-16,  6.52256027e-16,  1.00000000e+00,
         3.33934269e-17, -4.78783679e-16,  1.38777878e-17],
       [-6.28511555e-16, -1.58773497e-15, -5.93433697e-16,
         1.00000000e+00, -8.36591091e-16, -1.11647569e-17],
       [ 7.52577210e-16,  4.95309852e-16, -1.44660111e-16,
        -1.05273787e-17,  1.00000000e+00,  8.05536959e-18],
       [-2.63677968e-16,  1.38777878e-17,  2.42861287e-17,
        -1.08420217e-17,  1.87350135e-16,  1.00000000e+00]])

In [136]:
x = np.dot(A_inverse, b)

In [137]:
x

array([-0.40792601,  0.42119903,  1.05068463,  0.41796394,  0.41876593,
        0.6415843 ])

# За допомогою LU декомпозиції та методу Гаусса

In [138]:
P, L, U = linalg.lu(A)

In [139]:
P

array([[0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [140]:
L

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.01923077,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.21153846,  0.04288653,  1.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.25625   ,  0.01856702,  0.10228751,  1.        ,  0.        ,
         0.        ],
       [ 0.08076923, -0.58771958, -0.08004336,  0.53486436,  1.        ,
         0.        ],
       [ 0.00298077, -0.02466292, -0.10994791,  0.18474583, -0.60563355,
         1.        ]])

In [141]:
U

array([[ 2.08000000e+02,  4.00000000e-01, -8.80000000e+00,
         2.21600000e+02, -0.00000000e+00, -4.20000000e+00],
       [ 0.00000000e+00, -4.86076923e+01,  4.32923077e+00,
        -6.66153846e+00,  5.98000000e+01, -3.99230769e-01],
       [ 0.00000000e+00,  0.00000000e+00,  6.42758728e+01,
        -5.91912328e+01, -2.06461465e+00, -2.09441684e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -5.30067912e+01,  4.41008765e+01,  6.97895212e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.13923848e+01,  1.63671584e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  1.27425881e+01]])

In [142]:
def gaussian_elemination_lower(matrix, coefficients_vector):
    x = []
    for i in np.arange(matrix.shape[0]):
        j = i - 1
        sum_i = 0
        while j >= 0:
            sum_i += x[j]*matrix[i][j]
            j -= 1 
        x_i = (coefficients_vector[i] - sum_i)/matrix[i][i]
        x.append(x_i)
    return np.array(x)

def gaussian_elemination_upper(matrix, coefficients_vector):
    x = []
    for i in np.arange(matrix.shape[0] - 1, -1, -1):
        j = i + 1
        sum_i = 0
        while j <= matrix.shape[0] - 1:
            sum_i += x[matrix.shape[0] -1 - j]*matrix[i][j]
            j += 1 
        x_i = (coefficients_vector[i] - sum_i)/matrix[i][i]
        x.append(x_i)
    x = x[::-1]
    return np.array(x)

In [143]:
y = gaussian_elemination_lower(L, np.dot(np.linalg.inv(P), b))
x = gaussian_elemination_upper(U, y)

In [144]:
x

array([-0.40792601,  0.42119903,  1.05068463,  0.41796394,  0.41876593,
        0.6415843 ])

# Ітераційні методи

# Метод Якобі

In [145]:
D = np.zeros(A.shape)
np.fill_diagonal(D, np.diagonal(A))

In [146]:
D

array([[ 53.3,   0. ,   0. ,   0. ,   0. ,   0. ],
       [  0. ,  28.6,   0. ,   0. ,   0. ,   0. ],
       [  0. ,   0. ,  62.6,   0. ,   0. ,   0. ],
       [  0. ,   0. ,   0. , 221.6,   0. ,   0. ],
       [  0. ,   0. ,   0. ,   0. ,  59.8,   0. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,  13. ]])

In [147]:
A-D

array([[  0.  ,  -0.8 ,   4.4 ,  -2.4 ,  45.  ,  -0.6 ],
       [ 16.8 ,   0.  ,  -8.4 ,  -1.8 ,  -0.  ,   0.6 ],
       [ 44.  ,  -2.  ,   0.  , -12.6 ,   0.5 ,  -3.  ],
       [208.  ,   0.4 ,  -8.8 ,   0.  ,  -0.  ,  -4.2 ],
       [  4.  , -48.6 ,   4.16,  -2.4 ,   0.  ,  -0.48],
       [  0.62,   1.2 ,  -7.2 ,  -2.46,   0.  ,   0.  ]])

In [148]:
def invert_diagonal_matrix(matrix):
    matrix_inv = np.copy(matrix)
    for i in np.arange(matrix.shape[0]):
        matrix_inv[i][i] = 1/matrix[i][i]
    return matrix_inv

In [149]:
D_inv = invert_diagonal_matrix(D)

In [150]:
D_inv

array([[0.01876173, 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.03496503, 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.01597444, 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.00451264, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.01672241,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.07692308]])

In [151]:
Q = -np.matmul(D_inv, A-D)

In [152]:
Q

array([[-0.        ,  0.01500938, -0.08255159,  0.04502814, -0.84427767,
         0.01125704],
       [-0.58741259, -0.        ,  0.29370629,  0.06293706, -0.        ,
        -0.02097902],
       [-0.7028754 ,  0.03194888, -0.        ,  0.20127796, -0.00798722,
         0.04792332],
       [-0.93862816, -0.00180505,  0.03971119, -0.        , -0.        ,
         0.01895307],
       [-0.06688963,  0.81270903, -0.06956522,  0.04013378, -0.        ,
         0.00802676],
       [-0.04769231, -0.09230769,  0.55384615,  0.18923077, -0.        ,
        -0.        ]])

In [153]:
def matrix_norm(matrix):
    return np.max([np.sum(np.abs(matrix[i])) for i in np.arange(matrix.shape[0])])

def vector_norm(vector):
    return np.max(np.abs(vector))

In [154]:
matrix_norm(Q)

0.9990974729241878

In [155]:
f = np.dot(D_inv, b)

In [156]:
f

array([ 0.        , -0.13986014,  0.63897764, -0.01805054,  0.10033445,
        0.        ])

In [157]:
def jacobi_method(matrix, vector, epsilon, starting_approximation):
    y = starting_approximation
    epsilon_k = 10
    k = 0
    while epsilon_k >= epsilon:
        x_k = np.copy(y)
        x_k = np.dot(matrix, y) + vector
        epsilon_k = vector_norm(x_k - y)
        y = x_k
        k += 1
    print(f"Похибка останньої ітерації: {epsilon_k}")
    print(f"Кількість ітерацій: {k}")
    print(f"Нев`язок: {vector_norm(np.dot(matrix, x_k) + f - x_k)}")
    return x_k

In [158]:
jacobi_method(Q, f, 10**(-2), f)

Похибка останньої ітерації: 0.009984169367141194
Кількість ітерацій: 15
Нев`язок: 0.008256646959375835


array([-0.33600122,  0.34374108,  0.97096967,  0.33817176,  0.34458989,
        0.57921516])

In [159]:
jacobi_method(Q, f, 10**(-3), f)

Похибка останньої ітерації: 0.0009754785118092357
Кількість ітерацій: 35
Нев`язок: 0.0008693309564097862


array([-0.40079467,  0.41345249,  1.04270982,  0.40998013,  0.41137244,
        0.63535316])

In [160]:
jacobi_method(Q, f, 10**(-4), f)

Похибка останньої ітерації: 9.72389965646081e-05
Кількість ітерацій: 55
Нев`язок: 8.66497631322738e-05


array([-0.40721529,  0.42042699,  1.04988984,  0.41716825,  0.41802908,
        0.64096328])

In [161]:
jacobi_method(Q, f, 10**(-5), f)

Похибка останньої ітерації: 9.691035538217374e-06
Кількість ітерацій: 75
Нев`язок: 8.635682230917485e-06


array([-0.40785517,  0.42112209,  1.05060542,  0.41788464,  0.4186925 ,
        0.64152241])

In [162]:
jacobi_method(Q, f, 10**(-6), f)

Похибка останньої ітерації: 9.658273284474106e-07
Кількість ітерацій: 95
Нев`язок: 8.60648775025119e-07


array([-0.40791895,  0.42119136,  1.05067674,  0.41795603,  0.41875861,
        0.64157813])

In [163]:
jacobi_method(Q, f, 10**(-2), np.zeros(6))

Похибка останньої ітерації: 0.009984169367141194
Кількість ітерацій: 16
Нев`язок: 0.008256646959375835


array([-0.33600122,  0.34374108,  0.97096967,  0.33817176,  0.34458989,
        0.57921516])

In [164]:
jacobi_method(Q, f, 10**(-3), np.zeros(6))

Похибка останньої ітерації: 0.0009754785118092357
Кількість ітерацій: 36
Нев`язок: 0.0008693309564097862


array([-0.40079467,  0.41345249,  1.04270982,  0.40998013,  0.41137244,
        0.63535316])

In [165]:
jacobi_method(Q, f, 10**(-4), np.zeros(6))

Похибка останньої ітерації: 9.72389965646081e-05
Кількість ітерацій: 56
Нев`язок: 8.66497631322738e-05


array([-0.40721529,  0.42042699,  1.04988984,  0.41716825,  0.41802908,
        0.64096328])

In [166]:
jacobi_method(Q, f, 10**(-5), np.zeros(6))

Похибка останньої ітерації: 9.691035538217374e-06
Кількість ітерацій: 76
Нев`язок: 8.635682230917485e-06


array([-0.40785517,  0.42112209,  1.05060542,  0.41788464,  0.4186925 ,
        0.64152241])

In [167]:
jacobi_method(Q, f, 10**(-6), np.zeros(6))

Похибка останньої ітерації: 9.658273284474106e-07
Кількість ітерацій: 96
Нев`язок: 8.60648775025119e-07


array([-0.40791895,  0.42119136,  1.05067674,  0.41795603,  0.41875861,
        0.64157813])

# Метод Зейделя

In [168]:
def seidel_method(matrix, vector, epsilon, starting_approximation):
    y = starting_approximation
    epsilon_k = 10
    k = 0
    while epsilon_k >= epsilon:
        x_k = np.copy(y)
        for i in np.arange(matrix.shape[0]):
            sum_left = 0
            sum_right = 0
            for j in np.arange(i):
                sum_left += (matrix[i][j]*x_k[j])
            for j in np.arange(i + 1, matrix.shape[0]):
                sum_right += (matrix[i][j]*y[j])
            x_k[i] = sum_left + sum_right + vector[i]
        epsilon_k = vector_norm(x_k - y)
        y = x_k
        k += 1
    print(f"Похибка останньої ітерації: {epsilon_k}")
    print(f"Кількість ітерацій: {k}")
    print(f"Нев`язок: {vector_norm(np.dot(matrix, x_k) + f - x_k)}")
    return x_k

In [169]:
seidel_method(Q, f, 10**(-2), f)

Похибка останньої ітерації: 0.008449770294843173
Кількість ітерацій: 10
Нев`язок: 0.006223334658536139


array([-0.38101705,  0.39311296,  1.02291738,  0.39118262,  0.39479717,
        0.62244688])

In [170]:
seidel_method(Q, f, 10**(-3), f)

Похибка останньої ітерації: 0.0007921146025878789
Кількість ітерацій: 19
Нев`язок: 0.0005833989720773203


array([-0.40540347,  0.41856615,  1.04808164,  0.41545337,  0.41651902,
        0.6397903 ])

In [171]:
seidel_method(Q, f, 10**(-4), f)

Похибка останньої ітерації: 9.659547831819548e-05
Кількість ітерацій: 27
Нев`язок: 7.114337063612863e-05


array([-0.40761839,  0.42087796,  1.05036721,  0.41765778,  0.41849193,
        0.64136553])

In [172]:
seidel_method(Q, f, 10**(-5), f)

Похибка останньої ітерації: 9.055171339977797e-06
Кількість ітерацій: 36
Нев`язок: 6.669208766629797e-06


array([-0.40789717,  0.42116893,  1.05065487,  0.41793524,  0.41874025,
        0.64156379])

In [173]:
seidel_method(Q, f, 10**(-6), f)

Похибка останньої ітерації: 8.488609346546383e-07
Кількість ітерацій: 45
Нев`язок: 6.251931161660451e-07


array([-0.4079233 ,  0.42119621,  1.05068184,  0.41796125,  0.41876353,
        0.64158238])

In [174]:
seidel_method(Q, f, 10**(-2), np.zeros(6))

Похибка останньої ітерації: 0.00845413339739165
Кількість ітерацій: 12
Нев`язок: 0.006226540953543913


array([-0.38100329,  0.39309863,  1.02290321,  0.39116893,  0.39478494,
        0.6224371 ])

In [175]:
seidel_method(Q, f, 10**(-3), np.zeros(6))

Похибка останньої ітерації: 0.0007925189457878012
Кількість ітерацій: 21
Нев`язок: 0.000583696774195952


array([-0.40540218,  0.41856481,  1.04808031,  0.41545209,  0.41651788,
        0.63978938])

In [176]:
seidel_method(Q, f, 10**(-4), np.zeros(6))

Похибка останньої ітерації: 9.664478649007435e-05
Кількість ітерацій: 29
Нев`язок: 7.117968651360052e-05


array([-0.40761823,  0.4208778 ,  1.05036704,  0.41765763,  0.41849179,
        0.64136542])

In [177]:
seidel_method(Q, f, 10**(-5), np.zeros(6))

Похибка останньої ітерації: 9.059793647181458e-06
Кількість ітерацій: 38
Нев`язок: 6.672613134139915e-06


array([-0.40789715,  0.42116892,  1.05065486,  0.41793522,  0.41874023,
        0.64156378])

In [178]:
seidel_method(Q, f, 10**(-6), np.zeros(6))

Похибка останньої ітерації: 8.4929424459812e-07
Кількість ітерацій: 47
Нев`язок: 6.2551225249452e-07


array([-0.4079233 ,  0.42119621,  1.05068184,  0.41796125,  0.41876352,
        0.64158238])

# Метод релаксації

In [179]:
def succesive_over_relaxation(matrix, vector, omega, epsilon, 
                              starting_approximation):
    y = starting_approximation
    epsilon_k = 10
    k = 0
    while epsilon_k >= epsilon:
        x_k = np.copy(y)
        for i in np.arange(matrix.shape[0]):
            sum_left = 0
            sum_right = 0
            for j in np.arange(i):
                sum_left += (matrix[i][j]*x_k[j])
            for j in np.arange(i + 1, matrix.shape[0]):
                sum_right += (matrix[i][j]*y[j])
            x_k[i] = (1 - omega)*x_k[i] + omega*(sum_left + sum_right + vector[i])
        epsilon_k = vector_norm(x_k - y)
        y = x_k
        k += 1
    print(f"Похибка останньої ітерації: {epsilon_k}")
    print(f"Кількість ітерацій: {k}")
    print(f"Нев`язок: {vector_norm(np.dot(matrix, x_k) + f - x_k)}")
    return x_k

In [180]:
succesive_over_relaxation(Q, f, 1.5, 10**(-6), f)

Похибка останньої ітерації: 9.646290466402974e-07
Кількість ітерацій: 85
Нев`язок: 4.615928574924766e-07


array([-0.40792614,  0.42119899,  1.05068518,  0.41796387,  0.41876573,
        0.64158454])

In [181]:
succesive_over_relaxation(Q, f, 1.6, 10**(-6), f)

Похибка останньої ітерації: 8.950063272727959e-07
Кількість ітерацій: 1020
Нев`язок: 5.133692873027229e-07


array([-0.4079259 ,  0.42119906,  1.05068407,  0.41796409,  0.41876614,
        0.64158421])

In [182]:
succesive_over_relaxation(Q, f, 1.4, 10**(-6), f)

Похибка останньої ітерації: 6.792438624891872e-07
Кількість ітерацій: 44
Нев`язок: 2.0375013676243725e-07


array([-0.40792605,  0.42119905,  1.05068451,  0.41796416,  0.418766  ,
        0.64158443])

In [183]:
succesive_over_relaxation(Q, f, 1.3, 10**(-6), f)

Похибка останньої ітерації: 8.713298071949538e-07
Кількість ітерацій: 26
Нев`язок: 2.8333025176019433e-07


array([-0.4079262 ,  0.42119898,  1.05068499,  0.41796413,  0.4187658 ,
        0.64158468])

In [184]:
succesive_over_relaxation(Q, f, 1.2, 10**(-6), f)

Похибка останньої ітерації: 8.398626875072424e-07
Кількість ітерацій: 26
Нев`язок: 4.254957606808496e-07


array([-0.40792467,  0.42119768,  1.05068334,  0.41796274,  0.41876488,
        0.6415835 ])

In [185]:
succesive_over_relaxation(Q, f, 1.25, 10**(-6), f)

Похибка останньої ітерації: 6.02656538561952e-07
Кількість ітерацій: 22
Нев`язок: 4.3466170807082705e-07


array([-0.40792515,  0.42119836,  1.05068396,  0.41796302,  0.41876543,
        0.64158368])

In [186]:
succesive_over_relaxation(Q, f, 1.25, 10**(-6), np.zeros(6))

Похибка останньої ітерації: 7.989250284112792e-07
Кількість ітерацій: 24
Нев`язок: 3.3844858382536813e-07


array([-0.40792535,  0.42119848,  1.05068386,  0.41796344,  0.41876559,
        0.64158383])